### ISSUE TITLE
This addon is largely useless

### ISSUE THREAD

**Issue by pcsagan** [jordonwow/safequeue#10]
This addon does not address the broke Join Battleground issue, nor does it even respect its own minimize button.

Could you do the world a favor and delete this repository? It's basically false advertising, and nothing good comes from installing this software.

**Comment by jordonwow** [comment]
This solves the broken join button in 90% of use cases (taint caused from static popups). It essentially just clicks the minimap's enter button. Blizzard's retail code for joining battlegrounds functions similarly. A few addons (usually bad ports) taint the UIDropDown, which means the minimap's enter will also be blocked, whether SafeQueue is installed or not. Unfortunately there is no way around that for the time being other than to reload the UI. Since it seems you have a talent for complaining could you do the world a favor and request Blizzard remove AcceptBattlefieldPort() from their protected list?
