### ISSUE TITLE
Questie still blocks queue pops sometimes

### ISSUE THREAD

**Issue by hanbi-wow** [jordonwow/safequeue#9]
It started happening during arena queues for me, not sure if it happens with BGs too. Have to reload to be able to join, right-click enter battle on the icon is also buggered.

**Comment by slumpedgg** [comment]
also having this issue

**Comment by Hasselshoff** [comment]
I also am having this issue with latest versions of both SafeQueue (v5.1) & Questie (v6.5.1)

**Comment by Hasselshoff** [comment]
3 observations from my experience:

1) I just encountered another error preventing the SafeQueue button from working, this time with TomTom.

2) In retrospect, I should have mentioned this in my initial commnent. Every time the SafeQueue button didn't work (which was at least 5 times), neither did the default BG queue button in the minimap. There were yet still other times when the SafeQueue button worked, even with Questie enabled.

3) Prior to installing SafeQueue 2 days ago, I always had to use the BG minimap button, because the default button never works (which is well known of course, hence the need for SafeQueue in the first place). I honestly think the BG minimap button is itself experiencing a taint error that is unrelated to SafeQueue, because IIRC I had to reload my UI a couple times prior to using SafeQueue, because both the main Enter Battle button and the BG minimap button were broken.

![image](https://user-images.githubusercontent.com/69090157/128573129-ba764fdb-1aa4-4394-be66-04297a84beb2.png)
